//Type FETCH LIST
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';

//Categories
export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

//Manufacturers
export const FETCH_MANUFACTURER_LIST = 'FETCH_MANUFACTURER_LIST';
export const CREATE_MANUFACTURER = 'CREATE_MANUFACTURER';
export const UPDATE_MANUFACTURER = 'UPDATE_MANUFACTURER';
export const DELETE_MANUFACTURER = 'DELETE_MANUFACTURER';

//Account
export const FETCH_ACCOUNT_LIST = 'FETCH_ACCOUNT_LIST';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

// Check user login & signup
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Action types

export const FETCH_CART_LIST = 'FETCH_CART_LIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

//Order
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';
